defaults = {
    'compLabels' : '',
    'educationRequire' : '本科',
    'jobPlace' : '未知',
    'jobSalary' : '0.5-1.2',
    'jobAdvantage' : '',
    'experienceRequire' : '不限',
    'jobLink' : '',
    'jobInfo' : '',
    'jobLabels' : '',
    'compLink' : '',
    'longitude' : '',
    'latitude' : '',
    'businessZones' : '',
    'compHome' : '',
    'compLogo' : '',
    'financeStage' : '',
    'keyword':'java',

}
