# Generated by Django 2.0.1 on 2018-02-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DigitizedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationRequire', models.CharField(max_length=300)),
                ('major', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('jobWantedPlace', models.CharField(max_length=300)),
                ('experienceRequire', models.CharField(max_length=300)),
                ('skill', models.CharField(max_length=300)),
            ],
        ),
    ]
