# Generated by Django 2.0.1 on 2018-02-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobId',
            field=models.IntegerField(unique=True),
        ),
    ]
