# Generated by Django 2.0.1 on 2018-02-26 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='DigitizedJob',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
