# Generated by Django 2.0.1 on 2018-02-03 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20180202_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitizedjob',
            name='Job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.Job'),
        ),
    ]
