# Generated by Django 2.0.1 on 2018-02-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20180226_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='clicktimes',
            field=models.IntegerField(default=0),
        ),
    ]
