# Generated by Django 2.0.1 on 2018-02-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20180203_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationRequire', models.CharField(max_length=300)),
                ('major', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('jobWantedPlace', models.CharField(max_length=300)),
                ('experienceRequire', models.CharField(max_length=300)),
                ('skill', models.CharField(max_length=300)),
            ],
        ),
    ]
