# Generated by Django 2.0.1 on 2018-02-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobName', models.CharField(max_length=30)),
                ('JobPlace', models.CharField(max_length=10)),
                ('JobSalary', models.CharField(max_length=10)),
                ('JobAdvantage', models.CharField(max_length=30)),
                ('releaseTime', models.CharField(max_length=30)),
                ('jobNeed', models.CharField(max_length=30)),
                ('educationRequire', models.CharField(max_length=30)),
                ('experienceRequire', models.CharField(max_length=30)),
                ('skillRequire', models.CharField(max_length=30)),
                ('jobLink', models.CharField(max_length=200)),
                ('jobInfo', models.TextField()),
                ('jobNature', models.CharField(max_length=20)),
                ('jobLabels', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationRequire', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('jobPlace', models.CharField(max_length=20)),
                ('experienceRequire', models.CharField(max_length=20)),
                ('skillRequire', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='username',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
